name: Automate Train

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 
env:
  WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
  HF_KEY: ${{ secrets.HF_KEY }}

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python train.py